version: 2.1

orbs:
  android: circleci/android@2.3.0

executors:
  android-docker:
    docker:
      - image: cimg/android:2023.08
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    resource_class: medium

jobs:
  test:
    executor: android-docker
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: jars-v1
      - android/restore-build-cache:
          cache-prefix: build-cache-v1
      - run:
          name: Install OpenJDK 21
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-21-jdk
            sudo update-java-alternatives -s java-1.21.0-openjdk-amd64 || echo "Java 21 not found, continuing with existing Java version"
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-gradle-cache:
          cache-prefix: jars-v1
      - android/save-build-cache:
          cache-prefix: build-cache-v1
      - run:
          name: Run Tests
          command: ./gradlew :composeApp:testDebugUnitTest
      - store_test_results:
          path: composeApp/build/test-results

workflows:
  version: 2
  test:
    jobs:
      - test