version: 2.1
orbs:
  android: circleci/android@3.1.0
  ruby: circleci/ruby@1.8.0

jobs:
  test:
    executor:
      name: android/android_docker
      resource_class: medium
      tag: 2024.01.1
    steps:
      - checkout
      # Restore caches
      - android/restore_gradle_cache:
          cache_prefix: jars-v1
      - android/restore_build_cache:
          cache_prefix: build-cache-v1
      # Setup Ruby and Fastlane
      - ruby/install:
          version: "3.1.2"
      - ruby/install-deps:
          key: gems-v1
      # Run tests using Fastlane
      - run:
          name: Run Tests via Fastlane
          command: bundle exec fastlane android test
      # Save caches
      - android/save_gradle_cache:
          cache_prefix: jars-v1
      - android/save_build_cache:
          cache_prefix: build-cache-v1
      # Store test results
      - store_test_results:
          path: composeApp/build/test-results

  deploy:
    executor:
      name: android/android_docker
      resource_class: medium
      tag: 2024.01.1
    steps:
      - checkout
      # Restore caches
      - android/restore_gradle_cache:
          cache_prefix: jars-v1
      - android/restore_build_cache:
          cache_prefix: build-cache-v1
      # Setup Ruby and Fastlane
      - ruby/install:
          version: "3.1.2"
      - ruby/install-deps:
          key: gems-v1
      # Setup signing keys
      - run:
          name: Decode Android keystore
          command: |
            echo $ANDROID_KEYSTORE_BASE64 | base64 -d > android-keystore.jks
      - run:
          name: Create keystore.properties
          command: |
            echo "storeFile=../android-keystore.jks" > keystore.properties
            echo "storePassword=$KEYSTORE_PASSWORD" >> keystore.properties
            echo "keyAlias=$KEY_ALIAS" >> keystore.properties
            echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
      # Setup Google Play service account
      - run:
          name: Decode Google Play service account
          command: |
            echo $GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_BASE64 | base64 -d > fastlane/google-play-service-account.json
      # Run deploy using Fastlane
      - run:
          name: Deploy to Google Play via Fastlane
          command: bundle exec fastlane android deploy
      # Save caches
      - android/save_gradle_cache:
          cache_prefix: jars-v1
      - android/save_build_cache:
          cache_prefix: build-cache-v1

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy
#          requires:
#            - test
#          filters:
#            branches:
#              only: main  # Only run deploy on main branch