version: 2.1
jobs:
  build:
    docker:
      - image: your-docker-registry/your-image-name:your-tag
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Verify Docker Image
          command: docker pull your-docker-registry/your-image-name:your-tag
      - run:
          name: Build Project
          command: your-build-command
workflows:
  version: 2
  build_and_test:
    jobs:
      - build