version: 2.1

orbs:
  android: circleci/android@2.0.3

jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: default
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: v1-dependencies
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-gradle-cache:
          cache-prefix: v1-dependencies
      - android/run-tests:
          test-command: ./gradlew :composeApp:testDebugUnitTest
      - store_test_results:
          path: composeApp/build/test-results

workflows:
  version: 2
  test:
    jobs:
      - test
