version: 2.1
orbs:
  android: circleci/android@3.1.0
  ruby: circleci/ruby@1.8.0
jobs:
  test:
    executor:
      name: android/android_docker
      resource_class: medium
      tag: 2024.01.1
    steps:
      - checkout
      # Restore caches
      - android/restore_gradle_cache:
          cache_prefix: jars-v1
      - android/restore_build_cache:
          cache_prefix: build-cache-v1
      # Setup Ruby and Fastlane
      - ruby/install:
          version: "3.1.2"
      - ruby/install-deps:
          key: gems-v1
      # Run tests using Fastlane
      - run:
          name: Run Tests via Fastlane
          command: bundle exec fastlane android test
      # Save caches
      - android/save_gradle_cache:
          cache_prefix: jars-v1
      - android/save_build_cache:
          cache_prefix: build-cache-v1
      # Store test results
      - store_test_results:
          path: composeApp/build/test-results
workflows:
  version: 2
  test:
    jobs:
      - test