version: 2.1

jobs:
  test:
    docker:
      - image: cimg/android:2023.08
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "composeApp/build.gradle.kts" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "composeApp/build.gradle.kts" }}
      - run:
          name: Set Java Version
          command: sudo update-java-alternatives -s java-1.21.0-openjdk-amd64 || echo "Java 21 not found, attempting to install."
      - run:
          name: Install OpenJDK 21
          command: sudo apt-get update && sudo apt-get install -y openjdk-21-jdk
      - run:
          name: Run Tests
          command: ./gradlew :composeApp:testDebugUnitTest
      - store_test_results:
          path: composeApp/build/test-results

workflows:
  version: 2
  test:
    jobs:
      - test
