version: 2.1
orbs:
  android: circleci/android@3.1.0
  ruby: circleci/ruby@1.8.0

jobs:
  test:
    executor:
      name: android/android-docker
      resource-class: medium
      tag: 2024.01.1
    steps:
      - checkout
      # Restore caches using custom commands
      - restore_gradle_cache
      # Setup Ruby and Fastlane
      - ruby/install:
          version: "3.1.2"
      - ruby/install-deps:
          key: gems-v1
      # Run tests using Fastlane
      - run:
          name: Run Tests via Fastlane
          command: bundle exec fastlane android test
      # Save caches using custom commands
      - save_gradle_cache
      # Store test results
      - store_test_results:
          path: composeApp/build/test-results

# Define custom commands for gradle cache
commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
  save_gradle_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

workflows:
  version: 2
  test:
    jobs:
      - test